name: 'Second Opinion'
description: 'Generates AI Code Reviews for Pull Requests'
inputs:
  azure-openai-api-endpoint:
    description: 'Azure OpenAI API Endpoint'
    required: true
  azure-openai-api-key:
    description: 'Azure OpenAI API Key'
    required: true
  api-version:
    description: 'OpenAI Model'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get code differences into a file
      run: git diff --no-prefix -U2000 --output diff.txt HEAD^1 HEAD
      shell: bash

    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
        cache: 'pip'
    - run: |
        pip install -r python/requirements.txt
      shell: bash

    - name: Run Second Opinion
      id: second-opinion
      env:
        AZURE_OPENAI_API_KEY: ${{ inputs.azure-openai-api-key }}
        AZURE_OPENAI_API_ENDPOINT: ${{ inputs.azure-openai-api-endpoint }}
        API_VERSION: ${{ inputs.api-version }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
      run: |
        output=$(python python/second_opinion.py diff.txt)
        echo "PAYLOAD<<EOF"$'\n'"$output"$'\n'EOF >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Give Opinion on PR
      uses: actions/github-script@v7
      env:
        PAYLOAD: ${{ steps.second-opinion.outputs.PAYLOAD }}
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.PAYLOAD
          })
      